export const products = [
  {
    id: 1,
    name: 'Artisan Leather Bag',
    description: 'Crafted from the finest Italian leather, this artisan bag combines timeless elegance with modern functionality. Each piece is handmade by master craftsmen with over 50 years of experience. Features include hand-stitched detailing, solid brass hardware, and a luxurious suede-lined interior. Perfect for the discerning professional who values quality and sophistication.',
    price: 299,
    category: 'Accessories',
    isNew: true,
    inStock: true,
    images: [
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&auto=format&fit=crop&q=80',
    ],
    features: ['Genuine Italian Leather', 'Hand-stitched Details', 'Brass Hardware', 'Suede Interior'],
    specifications: {
      Material: '100% Italian Leather',
      Dimensions: '15" x 11" x 4"',
      Weight: '2.5 lbs',
      Warranty: 'Lifetime',
    },
  },
  {
    id: 2,
    name: 'Minimal Gold Watch',
    description: 'A masterpiece of Swiss engineering, this minimal gold watch represents the pinnacle of horological excellence. The 18K gold case houses a precision automatic movement visible through the sapphire crystal caseback. Water-resistant to 100 meters with a scratch-resistant sapphire crystal face.',
    price: 499,
    category: 'Watches',
    isNew: false,
    inStock: true,
    images: [
      'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=800&auto=format&fit=crop&q=80',
    ],
    features: ['Swiss Movement', '18K Gold Case', 'Sapphire Crystal', 'Water Resistant'],
    specifications: {
      Movement: 'Swiss Automatic',
      Case: '18K Yellow Gold',
      'Water Resistance': '100m',
      'Crystal': 'Sapphire',
    },
  },
  {
    id: 3,
    name: 'Cashmere Scarf',
    description: 'Woven from the finest Mongolian cashmere, this luxurious scarf offers unparalleled softness and warmth. Each scarf undergoes a meticulous 12-step finishing process to ensure the ultimate in comfort and durability. The perfect accessory for any season.',
    price: 189,
    category: 'Apparel',
    isNew: true,
    inStock: true,
    images: [
      'https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1584670747417-594a9412fba5?w=800&auto=format&fit=crop&q=80',
    ],
    features: ['100% Cashmere', 'Hand-finished', 'Lightweight', 'All-season'],
    specifications: {
      Material: '100% Mongolian Cashmere',
      Dimensions: '70" x 14"',
      Weight: '6 oz',
      Care: 'Dry Clean Only',
    },
  },
  {
    id: 4,
    name: 'Designer Sunglasses',
    description: 'These designer sunglasses feature handcrafted acetate frames with polarized lenses providing 100% UV protection. The classic silhouette is updated with contemporary proportions, making them perfect for any face shape. Includes premium leather case and cleaning cloth.',
    price: 349,
    category: 'Accessories',
    isNew: false,
    inStock: true,
    images: [
      'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=800&auto=format&fit=crop&q=80',
    ],
    features: ['Polarized Lenses', '100% UV Protection', 'Handcrafted Frames', 'Premium Case'],
    specifications: {
      Frame: 'Italian Acetate',
      Lenses: 'Polarized Glass',
      'UV Protection': '100%',
      Includes: 'Case + Cloth',
    },
  },
  {
    id: 5,
    name: 'Silk Evening Dress',
    description: 'An exquisite evening dress crafted from pure mulberry silk. This stunning piece features hand-sewn beading and a flowing silhouette that flatters every figure. Perfect for galas, weddings, and special occasions.',
    price: 899,
    category: 'Apparel',
    isNew: true,
    inStock: true,
    images: [
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&auto=format&fit=crop&q=80',
    ],
    features: ['Pure Silk', 'Hand-sewn Beading', 'Flowing Silhouette', 'Couture Quality'],
    specifications: {
      Material: '100% Mulberry Silk',
      Lining: 'Silk Charmeuse',
      Care: 'Professional Clean',
      Origin: 'Made in Italy',
    },
  },
  {
    id: 6,
    name: 'Diamond Pendant Necklace',
    description: 'A breathtaking pendant featuring a brilliant-cut diamond set in 18K white gold. The delicate chain and elegant setting showcase the stone\'s natural fire and brilliance. Certified conflict-free with full GIA documentation.',
    price: 2499,
    category: 'Jewelry',
    isNew: false,
    inStock: true,
    images: [
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=800&auto=format&fit=crop&q=80',
    ],
    features: ['GIA Certified', '18K White Gold', 'Conflict-Free', 'Brilliant Cut'],
    specifications: {
      Diamond: '1.5 Carat',
      Clarity: 'VS1',
      Color: 'F',
      Chain: '18" White Gold',
    },
  },
];

export const categories = [
  { id: 1, name: 'Accessories', count: 24 },
  { id: 2, name: 'Watches', count: 18 },
  { id: 3, name: 'Apparel', count: 32 },
  { id: 4, name: 'Jewelry', count: 15 },
];
